# ############################################################################
# Makefile for building: qtwebview
# Generated by qmake (3.1) (Qt 5.15.7)
# Project:  qtwebview.pro
# Template: subdirs
# Command: /usr/local/bin/qmake -o Makefile qtwebview.pro
# ############################################################################

MAKEFILE      = Makefile

EQ            = =

first: make_first
QMAKE         = /usr/local/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /usr/local/bin/qmake -install qinstall
QINSTALL_PROGRAM = /usr/local/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = qtwebview1.0.0
DISTDIR = /Users/git/qtwebview/.obj/qtwebview1.0.0
SUBTARGETS    =  \
		sub-src \
		sub-examples \
		sub-tests


# ###### Custom Variables
EXPORT_VALID_ARCHS = x86_64
EXPORT_ACTIVE_ARCHS = $(filter $(EXPORT_VALID_ARCHS), $(ARCHS))
EXPORT_ARCH_ARGS = $(foreach arch, $(if $(EXPORT_ACTIVE_ARCHS), $(EXPORT_ACTIVE_ARCHS), $(EXPORT_VALID_ARCHS)), -arch $(arch))
EXPORT__PRO_FILE_ = /Users/git/qtwebview/qtwebview.pro

sub-src-qmake_all:  FORCE
	@test -d src/ || mkdir -p src/
	cd src/ && $(QMAKE) -o Makefile /Users/git/qtwebview/src/src.pro
	cd src/ && $(MAKE) -f Makefile qmake_all
sub-src: FORCE
	@test -d src/ || mkdir -p src/
	cd src/ && ( test -e Makefile || $(QMAKE) -o Makefile /Users/git/qtwebview/src/src.pro ) && $(MAKE) -f Makefile
sub-src-make_first: FORCE
	@test -d src/ || mkdir -p src/
	cd src/ && ( test -e Makefile || $(QMAKE) -o Makefile /Users/git/qtwebview/src/src.pro ) && $(MAKE) -f Makefile 
sub-src-all: FORCE
	@test -d src/ || mkdir -p src/
	cd src/ && ( test -e Makefile || $(QMAKE) -o Makefile /Users/git/qtwebview/src/src.pro ) && $(MAKE) -f Makefile all
sub-src-clean: FORCE
	@test -d src/ || mkdir -p src/
	cd src/ && ( test -e Makefile || $(QMAKE) -o Makefile /Users/git/qtwebview/src/src.pro ) && $(MAKE) -f Makefile clean
sub-src-distclean: FORCE
	@test -d src/ || mkdir -p src/
	cd src/ && ( test -e Makefile || $(QMAKE) -o Makefile /Users/git/qtwebview/src/src.pro ) && $(MAKE) -f Makefile distclean
sub-src-install_subtargets: FORCE
	@test -d src/ || mkdir -p src/
	cd src/ && ( test -e Makefile || $(QMAKE) -o Makefile /Users/git/qtwebview/src/src.pro ) && $(MAKE) -f Makefile install
sub-src-uninstall_subtargets: FORCE
	@test -d src/ || mkdir -p src/
	cd src/ && ( test -e Makefile || $(QMAKE) -o Makefile /Users/git/qtwebview/src/src.pro ) && $(MAKE) -f Makefile uninstall
sub-examples-qmake_all: sub-src-qmake_all FORCE
	@test -d examples/ || mkdir -p examples/
	cd examples/ && $(QMAKE) -o Makefile /Users/git/qtwebview/examples/examples.pro
	cd examples/ && $(MAKE) -f Makefile qmake_all
sub-examples: sub-src FORCE
	@test -d examples/ || mkdir -p examples/
	cd examples/ && ( test -e Makefile || $(QMAKE) -o Makefile /Users/git/qtwebview/examples/examples.pro ) && $(MAKE) -f Makefile
sub-examples-make_first: sub-src-make_first FORCE
	@test -d examples/ || mkdir -p examples/
	cd examples/ && ( test -e Makefile || $(QMAKE) -o Makefile /Users/git/qtwebview/examples/examples.pro ) && $(MAKE) -f Makefile 
sub-examples-all: sub-src-all FORCE
	@test -d examples/ || mkdir -p examples/
	cd examples/ && ( test -e Makefile || $(QMAKE) -o Makefile /Users/git/qtwebview/examples/examples.pro ) && $(MAKE) -f Makefile all
sub-examples-clean: sub-src-clean FORCE
	@test -d examples/ || mkdir -p examples/
	cd examples/ && ( test -e Makefile || $(QMAKE) -o Makefile /Users/git/qtwebview/examples/examples.pro ) && $(MAKE) -f Makefile clean
sub-examples-distclean: sub-src-distclean FORCE
	@test -d examples/ || mkdir -p examples/
	cd examples/ && ( test -e Makefile || $(QMAKE) -o Makefile /Users/git/qtwebview/examples/examples.pro ) && $(MAKE) -f Makefile distclean
sub-examples-install_subtargets: sub-src-install_subtargets FORCE
	@test -d examples/ || mkdir -p examples/
	cd examples/ && ( test -e Makefile || $(QMAKE) -o Makefile /Users/git/qtwebview/examples/examples.pro ) && $(MAKE) -f Makefile install
sub-examples-uninstall_subtargets: sub-src-uninstall_subtargets FORCE
	@test -d examples/ || mkdir -p examples/
	cd examples/ && ( test -e Makefile || $(QMAKE) -o Makefile /Users/git/qtwebview/examples/examples.pro ) && $(MAKE) -f Makefile uninstall
sub-tests-qmake_all: sub-src-qmake_all FORCE
	@test -d tests/ || mkdir -p tests/
	cd tests/ && $(QMAKE) -o Makefile /Users/git/qtwebview/tests/tests.pro
	cd tests/ && $(MAKE) -f Makefile qmake_all
sub-tests: sub-src FORCE
	@test -d tests/ || mkdir -p tests/
	cd tests/ && ( test -e Makefile || $(QMAKE) -o Makefile /Users/git/qtwebview/tests/tests.pro ) && $(MAKE) -f Makefile
sub-tests-make_first: sub-src-make_first FORCE
	@test -d tests/ || mkdir -p tests/
	cd tests/ && ( test -e Makefile || $(QMAKE) -o Makefile /Users/git/qtwebview/tests/tests.pro ) && $(MAKE) -f Makefile 
sub-tests-all: sub-src-all FORCE
	@test -d tests/ || mkdir -p tests/
	cd tests/ && ( test -e Makefile || $(QMAKE) -o Makefile /Users/git/qtwebview/tests/tests.pro ) && $(MAKE) -f Makefile all
sub-tests-clean: sub-src-clean FORCE
	@test -d tests/ || mkdir -p tests/
	cd tests/ && ( test -e Makefile || $(QMAKE) -o Makefile /Users/git/qtwebview/tests/tests.pro ) && $(MAKE) -f Makefile clean
sub-tests-distclean: sub-src-distclean FORCE
	@test -d tests/ || mkdir -p tests/
	cd tests/ && ( test -e Makefile || $(QMAKE) -o Makefile /Users/git/qtwebview/tests/tests.pro ) && $(MAKE) -f Makefile distclean
sub-tests-install_subtargets: sub-src-install_subtargets FORCE
	@test -d tests/ || mkdir -p tests/
	cd tests/ && ( test -e Makefile || $(QMAKE) -o Makefile /Users/git/qtwebview/tests/tests.pro ) && $(MAKE) -f Makefile install
sub-tests-uninstall_subtargets: sub-src-uninstall_subtargets FORCE
	@test -d tests/ || mkdir -p tests/
	cd tests/ && ( test -e Makefile || $(QMAKE) -o Makefile /Users/git/qtwebview/tests/tests.pro ) && $(MAKE) -f Makefile uninstall

Makefile: qtwebview.pro .qmake.conf .qmake.cache /usr/local/Cellar/qt@5/5.15.7/mkspecs/macx-clang/qmake.conf /usr/local/Cellar/qt@5/5.15.7/mkspecs/features/spec_pre.prf \
		/usr/local/Cellar/qt@5/5.15.7/mkspecs/qdevice.pri \
		/usr/local/Cellar/qt@5/5.15.7/mkspecs/features/device_config.prf \
		/usr/local/Cellar/qt@5/5.15.7/mkspecs/common/unix.conf \
		/usr/local/Cellar/qt@5/5.15.7/mkspecs/common/mac.conf \
		/usr/local/Cellar/qt@5/5.15.7/mkspecs/common/macx.conf \
		/usr/local/Cellar/qt@5/5.15.7/mkspecs/common/sanitize.conf \
		/usr/local/Cellar/qt@5/5.15.7/mkspecs/common/gcc-base.conf \
		/usr/local/Cellar/qt@5/5.15.7/mkspecs/common/gcc-base-mac.conf \
		/usr/local/Cellar/qt@5/5.15.7/mkspecs/common/clang.conf \
		/usr/local/Cellar/qt@5/5.15.7/mkspecs/common/clang-mac.conf \
		/usr/local/Cellar/qt@5/5.15.7/mkspecs/qconfig.pri \
		/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_3danimation.pri \
		/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_3danimation_private.pri \
		/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_3dcore.pri \
		/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_3dcore_private.pri \
		/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_3dextras.pri \
		/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_3dextras_private.pri \
		/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_3dinput.pri \
		/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_3dinput_private.pri \
		/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_3dlogic.pri \
		/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_3dquick.pri \
		/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_3dquick_private.pri \
		/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_3dquickanimation.pri \
		/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_3dquickextras.pri \
		/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_3dquickinput.pri \
		/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_3dquickrender.pri \
		/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_3drender.pri \
		/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_3drender_private.pri \
		/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_bluetooth.pri \
		/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_bodymovin_private.pri \
		/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_charts.pri \
		/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_charts_private.pri \
		/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_clipboard_support_private.pri \
		/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_core.pri \
		/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_core_private.pri \
		/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_datavisualization.pri \
		/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_datavisualization_private.pri \
		/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_dbus.pri \
		/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_designer.pri \
		/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_designer_private.pri \
		/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_gamepad.pri \
		/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_gamepad_private.pri \
		/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_graphics_support_private.pri \
		/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_gui.pri \
		/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_help.pri \
		/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_help_private.pri \
		/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_location.pri \
		/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_location_private.pri \
		/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_macextras.pri \
		/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_macextras_private.pri \
		/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_multimedia_private.pri \
		/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_network.pri \
		/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_network_private.pri \
		/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_networkauth.pri \
		/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_networkauth_private.pri \
		/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_nfc.pri \
		/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_nfc_private.pri \
		/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_opengl.pri \
		/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_pdf.pri \
		/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_pdf_private.pri \
		/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_pdfwidgets.pri \
		/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_pdfwidgets_private.pri \
		/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_positioning.pri \
		/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_positioning_private.pri \
		/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_positioningquick.pri \
		/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_positioningquick_private.pri \
		/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_purchasing.pri \
		/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_purchasing_private.pri \
		/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_qml.pri \
		/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_qml_private.pri \
		/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_qmlmodels.pri \
		/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_qmltest_private.pri \
		/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_quick.pri \
		/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_quick3d.pri \
		/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_quick3d_private.pri \
		/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_quick3dassetimport.pri \
		/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_quick3dassetimport_private.pri \
		/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_quick3drender.pri \
		/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_quick3drender_private.pri \
		/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_quick3druntimerender.pri \
		/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_quick3druntimerender_private.pri \
		/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_quick3dutils.pri \
		/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_quick3dutils_private.pri \
		/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_quick_private.pri \
		/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_quickshapes_private.pri \
		/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_quicktemplates2.pri \
		/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_remoteobjects.pri \
		/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_repparser.pri \
		/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_repparser_private.pri \
		/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_script.pri \
		/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_script_private.pri \
		/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_scripttools.pri \
		/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_scripttools_private.pri \
		/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_scxml.pri \
		/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_scxml_private.pri \
		/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_sensors.pri \
		/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_sensors_private.pri \
		/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_serialbus.pri \
		/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_serialbus_private.pri \
		/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_serialport.pri \
		/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_serialport_private.pri \
		/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_sql.pri \
		/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_svg.pri \
		/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_svg_private.pri \
		/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_testlib.pri \
		/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_texttospeech.pri \
		/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_texttospeech_private.pri \
		/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_uiplugin.pri \
		/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_uitools.pri \
		/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_uitools_private.pri \
		/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_virtualkeyboard.pri \
		/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_virtualkeyboard_private.pri \
		/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_webchannel.pri \
		/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_webchannel_private.pri \
		/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_webengine.pri \
		/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_webengine_private.pri \
		/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_webenginecore.pri \
		/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_websockets.pri \
		/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_websockets_private.pri \
		/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_webview.pri \
		/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_webview_private.pri \
		/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_widgets.pri \
		/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_xml.pri \
		/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		mkspecs/modules-inst/qt_lib_webview.pri \
		mkspecs/modules-inst/qt_lib_webview_private.pri \
		mkspecs/modules/qt_lib_webview.pri \
		mkspecs/modules-inst/qt_plugin_qtwebview_darwin.pri \
		mkspecs/modules/qt_plugin_qtwebview_darwin.pri \
		mkspecs/modules-inst/qt_plugin_qtwebview_webengine.pri \
		mkspecs/modules/qt_plugin_qtwebview_webengine.pri \
		/usr/local/Cellar/qt@5/5.15.7/mkspecs/features/qt_functions.prf \
		/usr/local/Cellar/qt@5/5.15.7/mkspecs/features/qt_config.prf \
		/usr/local/Cellar/qt@5/5.15.7/mkspecs/macx-clang/qmake.conf \
		/usr/local/Cellar/qt@5/5.15.7/mkspecs/features/spec_post.prf \
		/usr/local/Cellar/qt@5/5.15.7/mkspecs/qmodule.pri \
		/usr/local/Cellar/qt@5/5.15.7/mkspecs/features/qt_prefix_build_check.prf \
		/usr/local/Cellar/qt@5/5.15.7/mkspecs/features/qt_build_config.prf \
		.qmake.conf \
		.qmake.cache \
		.qmake.stash \
		/usr/local/Cellar/qt@5/5.15.7/mkspecs/features/exclusive_builds.prf \
		/usr/local/Cellar/qt@5/5.15.7/mkspecs/features/mac/sdk.prf \
		/usr/local/Cellar/qt@5/5.15.7/mkspecs/features/toolchain.prf \
		/usr/local/Cellar/qt@5/5.15.7/mkspecs/features/mac/toolchain.prf \
		/usr/local/Cellar/qt@5/5.15.7/mkspecs/features/default_pre.prf \
		/usr/local/Cellar/qt@5/5.15.7/mkspecs/features/mac/default_pre.prf \
		/usr/local/Cellar/qt@5/5.15.7/mkspecs/features/qt_configure.prf \
		/usr/local/Cellar/qt@5/5.15.7/mkspecs/features/qt_parts.prf \
		/usr/local/Cellar/qt@5/5.15.7/mkspecs/features/resolve_config.prf \
		/usr/local/Cellar/qt@5/5.15.7/mkspecs/features/default_post.prf \
		/usr/local/Cellar/qt@5/5.15.7/mkspecs/features/mac/default_post.prf \
		/usr/local/Cellar/qt@5/5.15.7/mkspecs/features/mac/objective_c.prf \
		/usr/local/Cellar/qt@5/5.15.7/mkspecs/features/exceptions_off.prf \
		/usr/local/Cellar/qt@5/5.15.7/mkspecs/features/qt_example_installs.prf \
		/usr/local/Cellar/qt@5/5.15.7/mkspecs/features/mac/no_warn_empty_obj_files.prf \
		/usr/local/Cellar/qt@5/5.15.7/mkspecs/features/precompile_header.prf \
		/usr/local/Cellar/qt@5/5.15.7/mkspecs/features/unix/largefile.prf \
		/usr/local/Cellar/qt@5/5.15.7/mkspecs/features/mac/mac.prf \
		/usr/local/Cellar/qt@5/5.15.7/mkspecs/features/warn_on.prf \
		/usr/local/Cellar/qt@5/5.15.7/mkspecs/features/qmake_use.prf \
		/usr/local/Cellar/qt@5/5.15.7/mkspecs/features/file_copies.prf \
		/usr/local/Cellar/qt@5/5.15.7/mkspecs/features/qt_build_extra.prf \
		/usr/local/Cellar/qt@5/5.15.7/mkspecs/features/qt_docs_targets.prf \
		/usr/local/Cellar/qt@5/5.15.7/mkspecs/features/mac/rez.prf \
		/usr/local/Cellar/qt@5/5.15.7/mkspecs/features/mac/asset_catalogs.prf \
		/usr/local/Cellar/qt@5/5.15.7/mkspecs/features/testcase_targets.prf \
		/usr/local/Cellar/qt@5/5.15.7/mkspecs/features/yacc.prf \
		/usr/local/Cellar/qt@5/5.15.7/mkspecs/features/lex.prf \
		qtwebview.pro
	$(QMAKE) -o Makefile qtwebview.pro
/usr/local/Cellar/qt@5/5.15.7/mkspecs/features/spec_pre.prf:
/usr/local/Cellar/qt@5/5.15.7/mkspecs/qdevice.pri:
/usr/local/Cellar/qt@5/5.15.7/mkspecs/features/device_config.prf:
/usr/local/Cellar/qt@5/5.15.7/mkspecs/common/unix.conf:
/usr/local/Cellar/qt@5/5.15.7/mkspecs/common/mac.conf:
/usr/local/Cellar/qt@5/5.15.7/mkspecs/common/macx.conf:
/usr/local/Cellar/qt@5/5.15.7/mkspecs/common/sanitize.conf:
/usr/local/Cellar/qt@5/5.15.7/mkspecs/common/gcc-base.conf:
/usr/local/Cellar/qt@5/5.15.7/mkspecs/common/gcc-base-mac.conf:
/usr/local/Cellar/qt@5/5.15.7/mkspecs/common/clang.conf:
/usr/local/Cellar/qt@5/5.15.7/mkspecs/common/clang-mac.conf:
/usr/local/Cellar/qt@5/5.15.7/mkspecs/qconfig.pri:
/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_3danimation.pri:
/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_3danimation_private.pri:
/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_3dcore.pri:
/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_3dcore_private.pri:
/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_3dextras.pri:
/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_3dextras_private.pri:
/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_3dinput.pri:
/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_3dinput_private.pri:
/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_3dlogic.pri:
/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_3dlogic_private.pri:
/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_3dquick.pri:
/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_3dquick_private.pri:
/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_3dquickanimation.pri:
/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_3dquickanimation_private.pri:
/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_3dquickextras.pri:
/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_3dquickextras_private.pri:
/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_3dquickinput.pri:
/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_3dquickinput_private.pri:
/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_3dquickrender.pri:
/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_3dquickrender_private.pri:
/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_3dquickscene2d.pri:
/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_3dquickscene2d_private.pri:
/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_3drender.pri:
/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_3drender_private.pri:
/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_bluetooth.pri:
/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_bluetooth_private.pri:
/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_bodymovin_private.pri:
/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_charts.pri:
/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_charts_private.pri:
/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_clipboard_support_private.pri:
/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_concurrent.pri:
/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_core.pri:
/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_core_private.pri:
/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_datavisualization.pri:
/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_datavisualization_private.pri:
/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_dbus.pri:
/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_designer.pri:
/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_designer_private.pri:
/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_designercomponents_private.pri:
/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_edid_support_private.pri:
/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_fb_support_private.pri:
/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_gamepad.pri:
/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_gamepad_private.pri:
/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_graphics_support_private.pri:
/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_gui.pri:
/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_gui_private.pri:
/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_help.pri:
/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_help_private.pri:
/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_location.pri:
/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_location_private.pri:
/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_macextras.pri:
/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_macextras_private.pri:
/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_multimedia.pri:
/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_multimedia_private.pri:
/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_multimediawidgets.pri:
/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_network.pri:
/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_network_private.pri:
/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_networkauth.pri:
/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_networkauth_private.pri:
/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_nfc.pri:
/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_nfc_private.pri:
/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_opengl.pri:
/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_packetprotocol_private.pri:
/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_pdf.pri:
/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_pdf_private.pri:
/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_pdfwidgets.pri:
/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_pdfwidgets_private.pri:
/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_positioning.pri:
/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_positioning_private.pri:
/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_positioningquick.pri:
/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_positioningquick_private.pri:
/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_printsupport.pri:
/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_purchasing.pri:
/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_purchasing_private.pri:
/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_qml.pri:
/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_qml_private.pri:
/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_qmldebug_private.pri:
/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_qmlmodels.pri:
/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_qmlmodels_private.pri:
/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_qmltest.pri:
/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_qmltest_private.pri:
/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_qmlworkerscript.pri:
/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_qmlworkerscript_private.pri:
/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_quick.pri:
/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_quick3d.pri:
/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_quick3d_private.pri:
/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_quick3dassetimport.pri:
/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_quick3dassetimport_private.pri:
/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_quick3drender.pri:
/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_quick3drender_private.pri:
/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_quick3druntimerender.pri:
/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_quick3druntimerender_private.pri:
/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_quick3dutils.pri:
/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_quick3dutils_private.pri:
/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_quick_private.pri:
/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_quickcontrols2.pri:
/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_quickparticles_private.pri:
/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_quickshapes_private.pri:
/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_quicktemplates2.pri:
/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_quickwidgets.pri:
/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_remoteobjects.pri:
/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_remoteobjects_private.pri:
/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_repparser.pri:
/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_repparser_private.pri:
/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_script.pri:
/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_script_private.pri:
/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_scripttools.pri:
/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_scripttools_private.pri:
/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_scxml.pri:
/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_scxml_private.pri:
/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_sensors.pri:
/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_sensors_private.pri:
/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_serialbus.pri:
/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_serialbus_private.pri:
/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_serialport.pri:
/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_serialport_private.pri:
/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_service_support_private.pri:
/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_sql.pri:
/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_sql_private.pri:
/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_svg.pri:
/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_svg_private.pri:
/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_testlib.pri:
/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_texttospeech.pri:
/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_texttospeech_private.pri:
/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_theme_support_private.pri:
/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_uiplugin.pri:
/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_uitools.pri:
/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_uitools_private.pri:
/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_virtualkeyboard.pri:
/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_virtualkeyboard_private.pri:
/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_webchannel.pri:
/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_webchannel_private.pri:
/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_webengine.pri:
/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_webengine_private.pri:
/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_webenginecore.pri:
/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_webenginecore_private.pri:
/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri:
/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_webenginewidgets.pri:
/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_websockets.pri:
/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_websockets_private.pri:
/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_webview.pri:
/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_webview_private.pri:
/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_widgets.pri:
/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_xml.pri:
/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_xml_private.pri:
/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_xmlpatterns.pri:
/usr/local/Cellar/qt@5/5.15.7/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
mkspecs/modules-inst/qt_lib_webview.pri:
mkspecs/modules-inst/qt_lib_webview_private.pri:
mkspecs/modules/qt_lib_webview.pri:
mkspecs/modules-inst/qt_plugin_qtwebview_darwin.pri:
mkspecs/modules/qt_plugin_qtwebview_darwin.pri:
mkspecs/modules-inst/qt_plugin_qtwebview_webengine.pri:
mkspecs/modules/qt_plugin_qtwebview_webengine.pri:
/usr/local/Cellar/qt@5/5.15.7/mkspecs/features/qt_functions.prf:
/usr/local/Cellar/qt@5/5.15.7/mkspecs/features/qt_config.prf:
/usr/local/Cellar/qt@5/5.15.7/mkspecs/macx-clang/qmake.conf:
/usr/local/Cellar/qt@5/5.15.7/mkspecs/features/spec_post.prf:
/usr/local/Cellar/qt@5/5.15.7/mkspecs/qmodule.pri:
/usr/local/Cellar/qt@5/5.15.7/mkspecs/features/qt_prefix_build_check.prf:
/usr/local/Cellar/qt@5/5.15.7/mkspecs/features/qt_build_config.prf:
.qmake.conf:
.qmake.cache:
.qmake.stash:
/usr/local/Cellar/qt@5/5.15.7/mkspecs/features/exclusive_builds.prf:
/usr/local/Cellar/qt@5/5.15.7/mkspecs/features/mac/sdk.prf:
/usr/local/Cellar/qt@5/5.15.7/mkspecs/features/toolchain.prf:
/usr/local/Cellar/qt@5/5.15.7/mkspecs/features/mac/toolchain.prf:
/usr/local/Cellar/qt@5/5.15.7/mkspecs/features/default_pre.prf:
/usr/local/Cellar/qt@5/5.15.7/mkspecs/features/mac/default_pre.prf:
/usr/local/Cellar/qt@5/5.15.7/mkspecs/features/qt_configure.prf:
/usr/local/Cellar/qt@5/5.15.7/mkspecs/features/qt_parts.prf:
/usr/local/Cellar/qt@5/5.15.7/mkspecs/features/resolve_config.prf:
/usr/local/Cellar/qt@5/5.15.7/mkspecs/features/default_post.prf:
/usr/local/Cellar/qt@5/5.15.7/mkspecs/features/mac/default_post.prf:
/usr/local/Cellar/qt@5/5.15.7/mkspecs/features/mac/objective_c.prf:
/usr/local/Cellar/qt@5/5.15.7/mkspecs/features/exceptions_off.prf:
/usr/local/Cellar/qt@5/5.15.7/mkspecs/features/qt_example_installs.prf:
/usr/local/Cellar/qt@5/5.15.7/mkspecs/features/mac/no_warn_empty_obj_files.prf:
/usr/local/Cellar/qt@5/5.15.7/mkspecs/features/precompile_header.prf:
/usr/local/Cellar/qt@5/5.15.7/mkspecs/features/unix/largefile.prf:
/usr/local/Cellar/qt@5/5.15.7/mkspecs/features/mac/mac.prf:
/usr/local/Cellar/qt@5/5.15.7/mkspecs/features/warn_on.prf:
/usr/local/Cellar/qt@5/5.15.7/mkspecs/features/qmake_use.prf:
/usr/local/Cellar/qt@5/5.15.7/mkspecs/features/file_copies.prf:
/usr/local/Cellar/qt@5/5.15.7/mkspecs/features/qt_build_extra.prf:
/usr/local/Cellar/qt@5/5.15.7/mkspecs/features/qt_docs_targets.prf:
/usr/local/Cellar/qt@5/5.15.7/mkspecs/features/mac/rez.prf:
/usr/local/Cellar/qt@5/5.15.7/mkspecs/features/mac/asset_catalogs.prf:
/usr/local/Cellar/qt@5/5.15.7/mkspecs/features/testcase_targets.prf:
/usr/local/Cellar/qt@5/5.15.7/mkspecs/features/yacc.prf:
/usr/local/Cellar/qt@5/5.15.7/mkspecs/features/lex.prf:
qtwebview.pro:
qmake: FORCE
	@$(QMAKE) -o Makefile qtwebview.pro

qmake_all: sub-src-qmake_all sub-examples-qmake_all sub-tests-qmake_all FORCE

make_first: sub-src-make_first  FORCE
all: sub-src-all sub-examples-all sub-tests-all  FORCE
clean: sub-src-clean sub-examples-clean sub-tests-clean  FORCE
distclean: sub-src-distclean sub-examples-distclean sub-tests-distclean  FORCE
	-$(DEL_FILE) Makefile
	-$(DEL_FILE) .qmake.cache config.cache config.log mkspecs/modules/*.pri mkspecs/modules-inst/*.pri .qmake.stash
install_subtargets: sub-src-install_subtargets FORCE
uninstall_subtargets: sub-src-uninstall_subtargets FORCE

xcodeproj:
	@$(QMAKE) -spec macx-xcode "$(EXPORT__PRO_FILE_)"

html_docs:
	$(MAKE) -f $(MAKEFILE) prepare_docs && $(MAKE) -f $(MAKEFILE) generate_docs

docs:
	$(MAKE) -f $(MAKEFILE) html_docs && $(MAKE) -f $(MAKEFILE) qch_docs

sub-src-install_html_docs:
	@test -d src/ || mkdir -p src/
	cd src/ && ( test -e Makefile || $(QMAKE) -o Makefile /Users/git/qtwebview/src/src.pro ) && $(MAKE) -f Makefile install_html_docs
install_html_docs: sub-src-install_html_docs

sub-src-uninstall_html_docs:
	@test -d src/ || mkdir -p src/
	cd src/ && ( test -e Makefile || $(QMAKE) -o Makefile /Users/git/qtwebview/src/src.pro ) && $(MAKE) -f Makefile uninstall_html_docs
uninstall_html_docs: sub-src-uninstall_html_docs

sub-src-install_qch_docs:
	@test -d src/ || mkdir -p src/
	cd src/ && ( test -e Makefile || $(QMAKE) -o Makefile /Users/git/qtwebview/src/src.pro ) && $(MAKE) -f Makefile install_qch_docs
install_qch_docs: sub-src-install_qch_docs

sub-src-uninstall_qch_docs:
	@test -d src/ || mkdir -p src/
	cd src/ && ( test -e Makefile || $(QMAKE) -o Makefile /Users/git/qtwebview/src/src.pro ) && $(MAKE) -f Makefile uninstall_qch_docs
uninstall_qch_docs: sub-src-uninstall_qch_docs

sub-src-install_docs:
	@test -d src/ || mkdir -p src/
	cd src/ && ( test -e Makefile || $(QMAKE) -o Makefile /Users/git/qtwebview/src/src.pro ) && $(MAKE) -f Makefile install_docs
install_docs: sub-src-install_docs

sub-src-uninstall_docs:
	@test -d src/ || mkdir -p src/
	cd src/ && ( test -e Makefile || $(QMAKE) -o Makefile /Users/git/qtwebview/src/src.pro ) && $(MAKE) -f Makefile uninstall_docs
uninstall_docs: sub-src-uninstall_docs

sub-src-qch_docs:
	@test -d src/ || mkdir -p src/
	cd src/ && ( test -e Makefile || $(QMAKE) -o Makefile /Users/git/qtwebview/src/src.pro ) && $(MAKE) -f Makefile qch_docs
qch_docs: sub-src-qch_docs

sub-src-prepare_docs:
	@test -d src/ || mkdir -p src/
	cd src/ && ( test -e Makefile || $(QMAKE) -o Makefile /Users/git/qtwebview/src/src.pro ) && $(MAKE) -f Makefile prepare_docs
prepare_docs: sub-src-prepare_docs

sub-src-generate_docs:
	@test -d src/ || mkdir -p src/
	cd src/ && ( test -e Makefile || $(QMAKE) -o Makefile /Users/git/qtwebview/src/src.pro ) && $(MAKE) -f Makefile generate_docs
generate_docs: sub-src-generate_docs

sub-src-check:
	@test -d src/ || mkdir -p src/
	cd src/ && ( test -e Makefile || $(QMAKE) -o Makefile /Users/git/qtwebview/src/src.pro ) && $(MAKE) -f Makefile check
check: sub-src-check

sub-src-benchmark:
	@test -d src/ || mkdir -p src/
	cd src/ && ( test -e Makefile || $(QMAKE) -o Makefile /Users/git/qtwebview/src/src.pro ) && $(MAKE) -f Makefile benchmark
benchmark: sub-src-benchmark
install:install_subtargets  FORCE

uninstall: uninstall_subtargets FORCE

FORCE:

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: sub-src-distdir sub-examples-distdir sub-tests-distdir FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents mkspecs/modules-inst/qt_lib_webview.pri mkspecs/modules-inst/qt_lib_webview_private.pri mkspecs/modules/qt_lib_webview.pri mkspecs/modules-inst/qt_plugin_qtwebview_darwin.pri mkspecs/modules/qt_plugin_qtwebview_darwin.pri mkspecs/modules-inst/qt_plugin_qtwebview_webengine.pri mkspecs/modules/qt_plugin_qtwebview_webengine.pri .qmake.conf .qmake.stash qtwebview.pro $(DISTDIR)/

sub-src-distdir: FORCE
	@test -d src/ || mkdir -p src/
	cd src/ && ( test -e Makefile || $(QMAKE) -o Makefile /Users/git/qtwebview/src/src.pro ) && $(MAKE) -e -f Makefile distdir DISTDIR=$(DISTDIR)/src

sub-examples-distdir: FORCE
	@test -d examples/ || mkdir -p examples/
	cd examples/ && ( test -e Makefile || $(QMAKE) -o Makefile /Users/git/qtwebview/examples/examples.pro ) && $(MAKE) -e -f Makefile distdir DISTDIR=$(DISTDIR)/examples

sub-tests-distdir: FORCE
	@test -d tests/ || mkdir -p tests/
	cd tests/ && ( test -e Makefile || $(QMAKE) -o Makefile /Users/git/qtwebview/tests/tests.pro ) && $(MAKE) -e -f Makefile distdir DISTDIR=$(DISTDIR)/tests

