# Generated by CMake

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.8)
   message(FATAL_ERROR "CMake >= 2.8.0 required")
endif()
if(CMAKE_VERSION VERSION_LESS "2.8.3")
   message(FATAL_ERROR "CMake >= 2.8.3 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.8.3...3.23)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

if(CMAKE_VERSION VERSION_LESS 3.0.0)
  message(FATAL_ERROR "This file relies on consumers using CMake 3.0.0 or greater.")
endif()

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_cmake_targets_defined "")
set(_cmake_targets_not_defined "")
set(_cmake_expected_targets "")
foreach(_cmake_expected_target IN ITEMS Qt6::WebView Qt6::WebViewPrivate)
  list(APPEND _cmake_expected_targets "${_cmake_expected_target}")
  if(TARGET "${_cmake_expected_target}")
    list(APPEND _cmake_targets_defined "${_cmake_expected_target}")
  else()
    list(APPEND _cmake_targets_not_defined "${_cmake_expected_target}")
  endif()
endforeach()
unset(_cmake_expected_target)
if(_cmake_targets_defined STREQUAL _cmake_expected_targets)
  unset(_cmake_targets_defined)
  unset(_cmake_targets_not_defined)
  unset(_cmake_expected_targets)
  unset(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT _cmake_targets_defined STREQUAL "")
  string(REPLACE ";" ", " _cmake_targets_defined_text "${_cmake_targets_defined}")
  string(REPLACE ";" ", " _cmake_targets_not_defined_text "${_cmake_targets_not_defined}")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_cmake_targets_defined_text}\nTargets not yet defined: ${_cmake_targets_not_defined_text}\n")
endif()
unset(_cmake_targets_defined)
unset(_cmake_targets_not_defined)
unset(_cmake_expected_targets)


# Create imported target Qt6::WebView
add_library(Qt6::WebView SHARED IMPORTED)
set_property(TARGET Qt6::WebView PROPERTY FRAMEWORK 1)

set_target_properties(Qt6::WebView PROPERTIES
  COMPATIBLE_INTERFACE_STRING "QT_MAJOR_VERSION"
  INTERFACE_COMPILE_DEFINITIONS "QT_WEBVIEW_LIB"
  INTERFACE_COMPILE_OPTIONS "-fPIC"
  INTERFACE_INCLUDE_DIRECTORIES "/Users/git/qtwebview/include;/Users/git/qtwebview/include/QtWebView;/Users/git/qtwebview/lib/QtWebView.framework/Headers"
  INTERFACE_LINK_LIBRARIES "Qt::Core;Qt::Gui"
  INTERFACE_QT_MAJOR_VERSION "6"
  INTERFACE_SOURCES "\$<\$<BOOL:\$<TARGET_PROPERTY:QT_CONSUMES_METATYPES>>:/Users/git/qtwebview/src/webview/meta_types/qt6webview_release_metatypes.json>"
  MODULE_PLUGIN_TYPES "webview"
  _qt_config_module_name "webview"
  _qt_is_public_module "TRUE"
  _qt_module_has_headers "ON"
  _qt_module_include_name "QtWebView"
  _qt_module_interface_name "WebView"
  _qt_package_name "Qt6WebView"
  _qt_package_version "6.4.0"
  _qt_private_module_target_name "WebViewPrivate"
)

# Create imported target Qt6::WebViewPrivate
add_library(Qt6::WebViewPrivate INTERFACE IMPORTED)

set_target_properties(Qt6::WebViewPrivate PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/Users/git/qtwebview/src/webview;/Users/git/qtwebview/include/QtWebView/6.4.0;/Users/git/qtwebview/include/QtWebView/6.4.0/QtWebView"
  INTERFACE_LINK_LIBRARIES "Qt::CorePrivate;Qt::GuiPrivate;Qt6::WebView"
  _qt_config_module_name "webview_private"
  _qt_is_private_module "TRUE"
  _qt_package_name "Qt6WebView"
  _qt_package_version "6.4.0"
  _qt_public_module_target_name "WebView"
)

# Import target "Qt6::WebView" for configuration "Release"
set_property(TARGET Qt6::WebView APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(Qt6::WebView PROPERTIES
  IMPORTED_LOCATION_RELEASE "/Users/git/qtwebview/lib/QtWebView.framework/Versions/A/QtWebView"
  IMPORTED_SONAME_RELEASE "@rpath/QtWebView.framework/Versions/A/QtWebView"
  )

# This file does not depend on other imported targets which have
# been exported from the same project but in a separate export set.

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
